apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-app-config
  namespace: chat-app
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "chatdb"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  MINIO_ENDPOINT: "http://minio-service:9000"
  MINIO_BUCKET: "chat-files"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"