apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secret
  namespace: chat-app
type: Opaque
data:
  DB_USERNAME: Y2hhdHVzZXI=  # chatuser
  DB_PASSWORD: Y2hhdHBhc3M=  # chatpass
  JWT_SECRET: bXlTZWNyZXRLZXkxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=  # mySecretKey123456789012345678901234567890
  MINIO_ACCESS_KEY: bWluaW9hZG1pbg==  # minioadmin
  MINIO_SECRET_KEY: bWluaW9hZG1pbg==  # minioadmin