apiVersion: v1
kind: Service
metadata:
  name: chat-app-service
  namespace: chat-app
  labels:
    app: chat-app
spec:
  selector:
    app: chat-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: chat-app-loadbalancer
  namespace: chat-app
  labels:
    app: chat-app
spec:
  selector:
    app: chat-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer